# fly.toml app configuration file generated for travis-pirozzini on 2024-07-12T15:16:59-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'travis-pirozzini'
primary_region = 'sea'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[experimental]
  cmd = ['start.sh']
  entrypoint = ['sh']
  auto_rollback = true

[build]

[[mounts]]
  source = 'data'
  destination = '/data'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[http_service.checks]]
    interval = "5s"
    grace_period = "4s"
    method = "post"
    path = "/health"
    protocol = "http"
    timeout = "5s"
    tls_skip_verify = false

[[services]]
  protocol = 'tcp'
  internal_port = 8080
  processes = ['app']

  [[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = '15s'
    timeout = '2s'
    grace_period = '1s'

  [[services.http_checks]]
    interval = '30s'
    timeout = '10s'
    grace_period = '60s'
    method = 'GET'
    path = '/healthcheck'
    protocol = 'http'
    tls_skip_verify = false 

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
